### ISSUE TITLE
"bin/SeikaSay.exe" can't be redistributed.

### ISSUE THREAD

**Issue by k896951** [mosamosa774/ScreenShotSpeakWindow#1]
Hi.
I'm a developer and publisher of SeikaCenter.

If "bin/SeikaSay.exe" was downloaded from hgotoh.jp, please do not include "SeikaSay.exe" in ScreenShotSpeakWindow.
I don't allow others to redistribute "SeikaSay.exe".

**Comment by mosamosa774** [comment]
I have removed corresponding file from this repository.
I'm sorry.

**Comment by k896951** [comment]
issue is gone.
Thanks for your quick action.
